interface digitCard {
  type: "digit";
  color: "red" | "blue" | "green" | "yellow";
  digit: 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9;
}

interface actionCard {
  type: "action";
  color: "red" | "blue" | "green" | "yellow";
  action: "reverse" | "skip" | "draw";
}

interface wildCard {
  type: "wild";
  action: "color" | "draw";
}

const cards: (digitCard | actionCard | wildCard)[] = [
  { type: "wild", action: "color" },
  { type: "wild", action: "color" },
  { type: "wild", action: "color" },
  { type: "wild", action: "color" },
  { type: "wild", action: "draw" },
  { type: "wild", action: "draw" },
  { type: "wild", action: "draw" },
  { type: "wild", action: "draw" },
  { type: "action", color: "red", action: "reverse" },
  { type: "action", color: "red", action: "reverse" },
  { type: "action", color: "red", action: "skip" },
  { type: "action", color: "red", action: "skip" },
  { type: "action", color: "red", action: "draw" },
  { type: "action", color: "red", action: "draw" },
  { type: "digit", color: "red", digit: 0 },
  { type: "digit", color: "red", digit: 1 },
  { type: "digit", color: "red", digit: 1 },
  { type: "digit", color: "red", digit: 2 },
  { type: "digit", color: "red", digit: 2 },
  { type: "digit", color: "red", digit: 3 },
  { type: "digit", color: "red", digit: 3 },
  { type: "digit", color: "red", digit: 4 },
  { type: "digit", color: "red", digit: 4 },
  { type: "digit", color: "red", digit: 5 },
  { type: "digit", color: "red", digit: 5 },
  { type: "digit", color: "red", digit: 6 },
  { type: "digit", color: "red", digit: 6 },
  { type: "digit", color: "red", digit: 7 },
  { type: "digit", color: "red", digit: 7 },
  { type: "digit", color: "red", digit: 8 },
  { type: "digit", color: "red", digit: 8 },
  { type: "digit", color: "red", digit: 9 },
  { type: "digit", color: "red", digit: 9 },
  { type: "action", color: "green", action: "reverse" },
  { type: "action", color: "green", action: "reverse" },
  { type: "action", color: "green", action: "skip" },
  { type: "action", color: "green", action: "skip" },
  { type: "action", color: "green", action: "draw" },
  { type: "action", color: "green", action: "draw" },
  { type: "digit", color: "green", digit: 0 },
  { type: "digit", color: "green", digit: 1 },
  { type: "digit", color: "green", digit: 1 },
  { type: "digit", color: "green", digit: 2 },
  { type: "digit", color: "green", digit: 2 },
  { type: "digit", color: "green", digit: 3 },
  { type: "digit", color: "green", digit: 3 },
  { type: "digit", color: "green", digit: 4 },
  { type: "digit", color: "green", digit: 4 },
  { type: "digit", color: "green", digit: 5 },
  { type: "digit", color: "green", digit: 5 },
  { type: "digit", color: "green", digit: 6 },
  { type: "digit", color: "green", digit: 6 },
  { type: "digit", color: "green", digit: 7 },
  { type: "digit", color: "green", digit: 7 },
  { type: "digit", color: "green", digit: 8 },
  { type: "digit", color: "green", digit: 8 },
  { type: "digit", color: "green", digit: 9 },
  { type: "digit", color: "green", digit: 9 },
  { type: "action", color: "yellow", action: "reverse" },
  { type: "action", color: "yellow", action: "reverse" },
  { type: "action", color: "yellow", action: "skip" },
  { type: "action", color: "yellow", action: "skip" },
  { type: "action", color: "yellow", action: "draw" },
  { type: "action", color: "yellow", action: "draw" },
  { type: "digit", color: "yellow", digit: 0 },
  { type: "digit", color: "yellow", digit: 1 },
  { type: "digit", color: "yellow", digit: 1 },
  { type: "digit", color: "yellow", digit: 2 },
  { type: "digit", color: "yellow", digit: 2 },
  { type: "digit", color: "yellow", digit: 3 },
  { type: "digit", color: "yellow", digit: 3 },
  { type: "digit", color: "yellow", digit: 4 },
  { type: "digit", color: "yellow", digit: 4 },
  { type: "digit", color: "yellow", digit: 5 },
  { type: "digit", color: "yellow", digit: 5 },
  { type: "digit", color: "yellow", digit: 6 },
  { type: "digit", color: "yellow", digit: 6 },
  { type: "digit", color: "yellow", digit: 7 },
  { type: "digit", color: "yellow", digit: 7 },
  { type: "digit", color: "yellow", digit: 8 },
  { type: "digit", color: "yellow", digit: 8 },
  { type: "digit", color: "yellow", digit: 9 },
  { type: "digit", color: "yellow", digit: 9 },
  { type: "action", color: "blue", action: "reverse" },
  { type: "action", color: "blue", action: "reverse" },
  { type: "action", color: "blue", action: "skip" },
  { type: "action", color: "blue", action: "skip" },
  { type: "action", color: "blue", action: "draw" },
  { type: "action", color: "blue", action: "draw" },
  { type: "digit", color: "blue", digit: 0 },
  { type: "digit", color: "blue", digit: 1 },
  { type: "digit", color: "blue", digit: 1 },
  { type: "digit", color: "blue", digit: 2 },
  { type: "digit", color: "blue", digit: 2 },
  { type: "digit", color: "blue", digit: 3 },
  { type: "digit", color: "blue", digit: 3 },
  { type: "digit", color: "blue", digit: 4 },
  { type: "digit", color: "blue", digit: 4 },
  { type: "digit", color: "blue", digit: 5 },
  { type: "digit", color: "blue", digit: 5 },
  { type: "digit", color: "blue", digit: 6 },
  { type: "digit", color: "blue", digit: 6 },
  { type: "digit", color: "blue", digit: 7 },
  { type: "digit", color: "blue", digit: 7 },
  { type: "digit", color: "blue", digit: 8 },
  { type: "digit", color: "blue", digit: 8 },
  { type: "digit", color: "blue", digit: 9 },
  { type: "digit", color: "blue", digit: 9 },
];

export default cards;
